#os:
# - linux
# - osx

dist: xenial
git:
  quiet: true
language: python
#python:
#  - '3.6'
#  - '3.7'
  #  # https://github.com/travis-ci/travis-ci/issues/9815
  #  dist: xenial
  #  sudo: true
#  - "3.8-dev" # 3.8 development branch
#  - "nightly" # currently points to 3.8-dev

matrix:
  include:
    #--------------------------------------------------------------------------------------------------
      # latest versions of package
    - name: "Python 3.6"
      python: '3.6'
      env:
      - NUMPY='numpy'

    - name: "Python 3.7"
      python: '3.7'
      env:
      - NUMPY='numpy'

    - name: "Python 3.8"
      python: '3.8'
      env:
      - NUMPY='numpy'


#-------------------------------------------------
# old-A

#before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq python-dev python-setuptools  python3-dev python3-setuptools libblas-dev liblapack-dev libatlas-base-dev gfortran
#
# command to install dependencies
#install: "pip install -r requirements.txt"
#
# command to run tests
#script: nosetests
#script: "python pyNastran/all_tests.py"
#-------------------------------------------------
#new-B
# per https://gist.github.com/dan-blanchard/7045057

#notifications:
#  email: false

# Setup anaconda
before_install:
 - sudo -H pip install auxlib


# per http://conda.pydata.org/docs/travis.html
install:
  # atlas
  - echo "python=$TRAVIS_PYTHON_VERSION ${NUMPY}"
  - sudo apt-get update
  - sudo apt-get install ${LIB} ${LIBH5} gfortran


  # if line per https://docs.travis-ci.com/user/multi-os/
  - echo "python version=$TRAVIS_PYTHON_VERSION"

#===install dependencies===
#-----------pip------------
  - pip install ${NUMPY}
  - pip list
#----------run-----------
  - python setup.py develop


# Run test
script:
  #- nosetests --with-cov --cov YOUR_PACKAGE_NAME_HERE --cov-config .coveragerc --logging-level=INFO
  - coverage run pyatmos/utils/test_atmosphere.py

# https://github.com/z4r/python-coveralls
# Calculate coverage
after_success:
  - ls
    # python-coverage
    #usage: coveralls [-h] [--coveralls_url COVERALLS_URL] [--base_dir BASE_DIR]
    #                 [--data_file DATA_FILE] [--config_file CONFIG_FILE]
    #                 [--coveralls_yaml COVERALLS_YAML] [--ignore-errors]
    #                 [--merge_file MERGE_FILE] [--nogit] [--skip_ssl_verify]
  #- coveralls --ignore-errors

#  - coveralls
  - codecov
#after_success:
#  - coveralls --config_file .coveragerc
